export const RESERVED_SLUGS = [
    // --- Core System / App ---
    "app",
    "admin",
    "root",
    "system",
    "internal",
    "private",
    "public",

    // --- Auth / User ---
    "auth",
    "login",
    "logout",
    "signout",
    "signin",
    "sign-in",
    "signup",
    "sign-up",
    "register",
    "registration",
    "forgot",
    "forgot-password",
    "reset",
    "reset-password",
    "verify",
    "verify-email",
    "confirm",
    "callback",

    // --- Dashboard / Settings ---
    "dashboard",
    "account",
    "profile",
    "settings",
    "preferences",
    "billing",
    "subscription",
    "checkout",
    "payments",
    "payment",
    "invoice",
    "invoices",

    // --- Your current protected routes ---
    "store",
    "new",

    // --- Common website pages (DE) ---
    "impressum",
    "datenschutz",
    "privacy",
    "privacy-policy",
    "terms",
    "agb",
    "tos",
    "widerruf",
    "cookie",
    "cookies",
    "kontakt",
    "contact",
    "about",
    "ueber-uns",
    "uber-uns",
    "hilfe",
    "help",
    "support",
    "faq",

    // --- Commerce / Shop ---
    "shop",
    "cart",
    "checkout",
    "order",
    "orders",
    "purchase",
    "purchases",
    "product",
    "products",
    "category",
    "categories",
    "collection",
    "collections",

    // --- Content / Blog ---
    "blog",
    "news",
    "posts",
    "post",
    "article",
    "articles",

    // --- Search / Discover ---
    "search",
    "explore",
    "discover",
    "trending",

    // --- Files / Tech ---
    "api",
    "graphql",
    "webhook",
    "webhooks",
    "assets",
    "static",
    "cdn",
    "media",
    "uploads",
    "download",
    "downloads",

    // --- Next.js / Browser special ---
    "_next",
    "favicon.ico",
    "favicon",
    "robots.txt",
    "robots",
    "sitemap.xml",
    "sitemap",

    // --- Common misc reserved ---
    "null",
    "undefined",
    "true",
    "false",
    "me",
    "you",
    "home",
    "index",
    "start",
    "welcome",
    "test",
    "dev",
    "demo",
];
